// apps/travel-guide/src/components/AuthGuard.tsx
'use client';

import { useState, useEffect, ReactNode } from 'react';
import { isLoggedIn } from '@/lib/auth';
import AuthModal from './AuthModal';

type AuthGuardProps = {
  children: ReactNode;
  mode?: 'optional' | 'required';
  onGuarded?: () => void;
};

export default function AuthGuard({ children, mode = 'optional', onGuarded }: AuthGuardProps) {
  const [showModal, setShowModal] = useState(false);
  const [authed, setAuthed] = useState(false);

  useEffect(() => {
    if (!isLoggedIn()) {
      setShowModal(true);
    } else {
      setAuthed(true);
    }
  }, []);

  const handleLogin = () => {
    setAuthed(true);
    setShowModal(false);
    onGuarded?.();
  };

  const handleClose = () => {
    setShowModal(false);
    if (mode === 'required' && !isLoggedIn()) {
      setShowModal(true);
    }
  };

  if (authed || isLoggedIn()) {
    return <>{children}</>;
  }

  return (
    <>
      {mode === 'optional' && children}
      <AuthModal
        open={showModal}
        onClose={handleClose}
        onLogin={handleLogin}
        force={mode === 'required'}
      />
    </>
  );
}

// apps/main-site/src/components/AuthGuard.vue
<script setup lang="ts">
import { ref, onMounted } from 'vue'
import { isLoggedIn } from '@/api/auth'
import AuthModal from './AuthModal.vue'

const props = withDefaults(defineProps<{
  mode?: 'optional' | 'required'
}>(), {
  mode: 'optional',
})

const emit = defineEmits<{
  guarded: []
}>()

const showModal = ref(false)
const authed = ref(false)

onMounted(() => {
  if (!isLoggedIn()) {
    showModal.value = true
  } else {
    authed.value = true
  }
})

function handleLogin() {
  authed.value = true
  showModal.value = false
  emit('guarded')
}

function handleClose() {
  showModal.value = false
  if (props.mode === 'required' && !isLoggedIn()) {
    showModal.value = true
  }
}
</script>

<template>
  <template v-if="authed || isLoggedIn()">
    <slot />
  </template>
  <template v-else>
    <template v-if="mode === 'optional'">
      <slot />
    </template>
    <AuthModal
      :open="showModal"
      :force="mode === 'required'"
      @close="handleClose"
      @login="handleLogin"
    />
  </template>
</template>
